configuration:
    - Release
before_build:
    - nuget restore
after_build:
    - nuget pack src\DbTester\DbTester.nuspec -Version %appveyor_build_version%
assembly_info:
    patch: true
    file: AssemblyInfo.cs
    assembly_version: "{version}"
    assembly_file_version: '{version}'
    assembly_informational_version: '{version}'
artifacts:
    - path: '**\DbIntegrationTester*.nupkg'
deploy:
    provider: NuGet
    api_key:
        secure: 'UVYy/xc+Oi13wfJa5fSB1XiHl61dJi8V0KyDbLLR03Koe9a8hvDvnpg/Q7BXUudo'
    skip_symbols: false
    artifact: /.*\.nupkg/
